# Generated by Django 2.0.2 on 2018-02-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_at', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
