# Generated by Django 2.0.2 on 2018-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_schedule', '0002_auto_20180204_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='member',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
